#ifndef DEFINES_H_
#define DEFINES_H_

enum AirShipDefines {
  BATTLE_CRUSER_HEALTH = 450,
  BATTLE_CRUSER_DAMAGE = 40,

  VIKING_HEALTH = 150,
  VIKING_DAMAGE = 15,

  CARRIER_HEALTH = 200,
  CARRIER_SHIELD = 150,
  CARRIER_DAMAGE = 8,
  CARRIER_SHIELD_REGENERATE_RATE = 40,

  PHOENIX_HEALTH = 90,
  PHOENIX_SHIELD = 90,
  PHOENIX_DAMAGE = 20,
  PHOENIX_SHIELD_REGENERATE_RATE = 20
};

enum AirShipType {
  BATTLE_CRUSER, VIKING, CARRIER, PHOENIX
};

enum CarrierDefines {
  MAX_INTERCEPTORS = 8,
  DAMAGED_STATUS_INTERCEPTORS = 4
};

enum BattleCruserDefines {
  YAMATO_CANNON_LOADING_TURNS = 4,
  YAMATO_CANNON_DAMAGE_MODIFIER = 5
};

enum VikingDefines {
  VIKING_DAMAGE_BONUS_AGAINST_PHOENIX = 2
};

enum AirShipProperties {
  SHIP_ID, SHIP_TYPE, SHIP_DAMAGE, 
  SHIP_HEALTH, YAMATO_CANNON_COUNTER, SHIP_SHIELD, 
  SHIP_REGENERATE_SHIELD_RATE,
  SHIP_INITIAL_SHIELD,
  SHIP_CARRIER_INTERCEPTORS_NUMBER
};

enum AirShipArraySizes {
  BATTLE_CRUSER_ARRAY_SIZE = 5, 
  VIKING_ARRAY_SIZE = 4, 
  CARRIER_ARRAY_SIZE = 9, 
  PHOENIX_ARRAY_SIZE = 8
};

#endif /* DEFINES_H_ */
